const EFFECT_TAG_UPDATE = 'UPDATE'
const EFFECT_TAG_INSERTION = 'INSERTION'
const EFFECT_TAG_DELETION = 'DELETION'

module.exports = {
  EFFECT_TAG_INSERTION,
  EFFECT_TAG_UPDATE,
  EFFECT_TAG_DELETION
}